name: Backend CI/CD

on:
  push:
    branches:
      #- main

jobs:
  backend-ci-cd:
    name: Backend Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Docker Image
        run: |
          docker build -t backend-api:latest -f backend/Dockerfile backend/

      - name: Run Backend Tests
        run: |
          docker run --rm backend-api:latest npm test

      - name: Deploy Backend to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          cd backend
          vercel --prod --token $VERCEL_TOKEN
